require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Lint/EmptyClass:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/UnreachableLoop:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/GuardClause:
  AllowConsecutiveConditionals: true

Style/NumericLiterals:
  Enabled: false

Style/SafeNavigation:
  MaxChainLength: 1

Style/SuperWithArgsParentheses:
  Enabled: false
